version: "3"
services:
        nginx:
                build: ./requirements/nginx/
                container_name: nginx
                image: nginx
                volumes:
                        - wordpress-volume:var/www/wordpress
                restart: unless-stopped
        wordpress:
                build: ./requirements/wordpress/
                container_name: wordpress
                image: wordpress
                depends_on:
                        - mariadb
                environment:
                volumes:
                        - wordpress-volume:/var/www/wordpress
                restart: unless-stopped
        mariadb:
                build: ./requirements/mariadb/
                container_name: mariadb
                image: mariadb
                volumes:
                        - ./mariadb-volume:/var/lib/mysql
                restart: unless-stopped
networks:
        default:
                external:
                        name: inet

volumes:
        mariadb-volume:
                driver: local
                driver_opts:
                        type: none
                        device: ${MARIADB_HOST_VOLUME_PATH}
                        o: bind
        wordpress-volume:
                driver: local
                driver_opts:
                        type: none
                        device: ${WORDPRESS_HOST_VOLUME_PATH}
                        o: bind
