version: "3"

volumes:
    wordpress-files:
        driver: local
        driver_opts:
            type: none
            device: $HOME/data/wordpress
            o: bind
    mariadb-data:
        driver: local
        driver_opts:
            type: none
            device: $HOME/data/mariadb
            o: bind

networks:
    mynetwork:

services:
 nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx/
        dockerfile: Dockerfile
    image: nginx
    ports:
        - 443:443
    env_file: 
        - .env
    networks:
        - mynetwork
    depends_on:
        - wordpress
    volumes:
        - wordpress-files:/var/www/html
    restart: always

 wordpress:
    tty: true
    container_name: wordpress
    build:
        context: ./requirements/wordpress/
        dockerfile: Dockerfile
    image: wordpress
    depends_on:
        - mariadb
    volumes:
        - wordpress-files:/var/www/html
    env_file: 
        - .env
    networks:
        - mynetwork
    restart: always

 mariadb:
    container_name: mariadb
    build:
        context: ./requirements/mariadb/
        dockerfile: Dockerfile
        args:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    image: mariadb
    volumes:
        - mariadb-data:/var/lib/mysql
    env_file: 
        - .env
    networks:
        - mynetwork
    restart: always

