version: "3"
services:
        nginx:
                image: nginx
                ports:
                        - "8081:80"
                restart: always
        wordpress:
                image: wordpress
                ports:
                        - "8089:80"
                depends_on:
                        - mysql
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD:  " "
                        WORDPRESS_DB_NAME: wordpress
                restart: always
        mysql:
                image: "mysql:5.7"
                enviroment:
                        MYSQL_DATABASE: wordpress
                volumes:
                        - ./mysql:/var/lib/mysql
networks:
        webpage:
        ipam:
                driver: default
                config:
                        - subnet: "10.200.223.223/24"