version: "3"
services:
 nginx:
  build:
    context: ./requirements/nginx/
    container_name: nginx
    dockerfile: nginx.Dockerfile
  ports:
    - 80:80
    - 443:443
  restart: unless-stopped
  enviroment:
    - SSL_CERT = ${CERTS_}
    - SSL_KEY = ${SSL_KEY} 
  networks:
    - mynetwork
  
 wordpress:
  build:
    context: ./requirements/wordpress/
    container_name: wordpress
    dockerfile: wordpress.Dockerfile
  depends_on:
    - mariadb
  volumes:
    - wordpress-files: /var/www/html
  restart: unless-stopped
  enviroment:
    - WORPRESS_DB_HOST = mariadb
    - WORPRESS_DB_USER = ${WORPRESS_DB_USER}
    - WORPRESS_DB_PASSWORD = ${WORPRESS_DB_PASSWORD}
    - WORPRESS_DB_NAME = ${WORPRESS_DB_NAME}
  networks:
    - mynetwork

 mariadb:
  build:
    context: ./requirements/mariadb/
    container_name: mariadb
  volumes:
    - ./mariadb-data:/var/lib/mysql
  enviroment:
      MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE = ${MYSQL_DATABASE}
      MYSQL_USER = ${MYSQL_USER}
      MYSQL_PASSWORD = ${MYSQL_PASSWORD}
  restart: unless-stopped
  networks:
    - mynetwork


volumes:
    wordpress-files:
    mariadb-data:

networks:
 mynetwork: