version: "3"
services:
 nginx:
  build:
    context: ./requirements/nginx/
    container_name: nginx
    dockerfile: nginx.Dockerfile
  ports:
    - 80:80
    - 443:443
  restart: unless-stopped
 wordpress:
  build:
    context: ./requirements/wordpress/
    container_name: wordpress
    dockerfile: wordpress.Dockerfile
    restart: unless-stopped
 mariadb:
  build:
    context: ./requirements/mariadb/
    container_name: mariadb
  volumes:
    - ./mariadb-data:/var/lib/mysql
  enviroment:
      MYSQL_ROOT_PASSWORD = "password"
  restart: unless-stopped



volumes:
    wordpress-files:
    mariadb-data:

networks:
 default:
  external:
   name: mynetwork