version: "3"
services:
 nginx:
  build:
    context: ./requirements/nginx/
    dockerfile: nginx.Dockerfile
  ports:
    - 80:80
    - 443:443
  env_file: 
    - .env
  restart: unless-stopped
  environment:
    - SSL_CERT = ${CERTS_}
    - SSL_KEY = ${SSL_KEY} 
  networks:
    - mynetwork
  
 wordpress:
  build:
    context: ./requirements/wordpress/
    dockerfile: wordpress.Dockerfile
  depends_on:
    - mariadb
  volumes:
    - "./wordpress-files:/var/www/html"
  env_file: 
    - .env
  restart: unless-stopped
  environment:
    - WORPRESS_DB_HOST = mariadb
    - WORPRESS_DB_USER = ${WORPRESS_DB_USER}
    - WORPRESS_DB_PASSWORD = ${WORPRESS_DB_PASSWORD}
    - WORPRESS_DB_NAME = ${WORPRESS_DB_NAME}
  networks:
    - mynetwork

 mariadb:
  build:
    context: ./requirements/mariadb/
  volumes:
    - "./mariadb-data:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE = ${MYSQL_DATABASE}
    - MYSQL_USER = ${MYSQL_USER}
    - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
  env_file: 
    - .env
  restart: unless-stopped
  networks:
    - mynetwork


volumes:
    wordpress-files:
    mariadb-data:

networks:
 mynetwork: