version: "3"

volumes:
    wordpress-files:
        name: 
        - wordpress
        driver: local
        driver_opts:
            type: none
            device: $HOME/data/wordpress
            o: bind
    mariadb-data:
        name:
        - mariadb
        driver: local
        driver_opts:
            type: none
            device: $HOME/data/mysql
            o: bind

networks:
    mynetwork:
        name:
        - inception

services:
 nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx/
        dockerfile: Dockerfile
    image: nginx
    ports:
        - 443:443
    env_file: 
        - .env
    networks:
        - mynetwork
    depends_on:
        - wordpress
    volumes:
        - wordpress-files:/var/www/html
    restart: unless-stopped

 wordpress:
    container_name: wordpress
    build:
        context: ./requirements/wordpress/
        dockerfile: Dockerfile
    image: wordpress
    depends_on:
        - mariadb
    volumes:
        - wordpress-files:/var/www/html
    env_file: 
        - .env
    networks:
        - mynetwork
    restart: unless-stopped

 mariadb:
    container_name: mariadb
    build:
        context: ./requirements/mariadb/
        dockerfile: Dockerfile
    image: mariadb
    volumes:
        - mariadb-data:/var/lib/mysql
    env_file: 
        - .env
    networks:
        - mynetwork
    restart: unless-stopped

