version: "3"
services:
 nginx:
  container_name: nginx
  build:
    context: ./requirements/nginx/
    dockerfile: Dockerfile
  ports:
    - 80:80
    - 443:443
  env_file: 
    - .env
  restart: unless-stopped
  environment:
    - SSL_CERT= ${CERTS_}
    - SSL_KEY= ${SSL_KEY} 
  networks:
    - mynetwork
  
 wordpress:
  container_name: wordpress
  build:
    context: ./requirements/wordpress/
    dockerfile: Dockerfile
  depends_on:
    - mariadb
  volumes:
    - "./wordpress-files:/var/www/html"
  env_file: 
    - .env
  restart: unless-stopped
  environment:
    - WORPRESS_DB_HOST= mariadb
    - WORPRESS_DB_USER= ${WORPRESS_DB_USER}
    - WORPRESS_DB_PASSWORD= ${WORPRESS_DB_PASSWORD}
    - WORPRESS_DB_NAME= ${WORPRESS_DB_NAME}
  networks:
    - mynetwork

 mariadb:
  container_name: mariadb
  build:
    context: ./requirements/mariadb/
    dockerfile: Dockerfile
  volumes:
    - "./mariadb-data:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE= ${MYSQL_DATABASE}
    - MYSQL_USER= ${MYSQL_USER}
    - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
  env_file: 
    - .env
  restart: unless-stopped
  networks:
    - mynetwork


volumes:
    wordpress-files:
    mariadb-data:

networks:
 mynetwork: